/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pipe_hla_SimDSPNModule_test_jni_Java2Cpp */

#ifndef _Included_pipe_hla_SimDSPNModule_test_jni_Java2Cpp
#define _Included_pipe_hla_SimDSPNModule_test_jni_Java2Cpp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pipe_hla_SimDSPNModule_test_jni_Java2Cpp
 * Method:    DLL_ADD
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_pipe_hla_SimDSPNModule_test_jni_Java2Cpp_DLL_1ADD
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     pipe_hla_SimDSPNModule_test_jni_Java2Cpp
 * Method:    DDL_SUB
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_pipe_hla_SimDSPNModule_test_jni_Java2Cpp_DDL_1SUB
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     pipe_hla_SimDSPNModule_test_jni_Java2Cpp
 * Method:    DDL_MUL
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_pipe_hla_SimDSPNModule_test_jni_Java2Cpp_DDL_1MUL
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     pipe_hla_SimDSPNModule_test_jni_Java2Cpp
 * Method:    DDL_DIV
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_pipe_hla_SimDSPNModule_test_jni_Java2Cpp_DDL_1DIV
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
