/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pipe_hla_SimDSPNModule_test_jni_MetisC2JTest */

#ifndef _Included_pipe_hla_SimDSPNModule_test_jni_MetisC2JTest
#define _Included_pipe_hla_SimDSPNModule_test_jni_MetisC2JTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pipe_hla_SimDSPNModule_test_jni_MetisC2JTest
 * Method:    DLL_ADD
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_pipe_hla_SimDSPNModule_test_jni_MetisC2JTest_DLL_1ADD
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     pipe_hla_SimDSPNModule_test_jni_MetisC2JTest
 * Method:    METIS_PartGraphKway
 * Signature: (II[I[II)[I
 */
JNIEXPORT jintArray JNICALL Java_pipe_hla_SimDSPNModule_test_jni_MetisC2JTest_METIS_1PartGraphKway
  (JNIEnv *, jobject, jint, jint, jintArray, jintArray, jint);

/*
 * Class:     pipe_hla_SimDSPNModule_test_jni_MetisC2JTest
 * Method:    Function
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_pipe_hla_SimDSPNModule_test_jni_MetisC2JTest_Function
  (JNIEnv *, jobject);

/*
 * Class:     pipe_hla_SimDSPNModule_test_jni_MetisC2JTest
 * Method:    Function2
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_pipe_hla_SimDSPNModule_test_jni_MetisC2JTest_Function2
  (JNIEnv *, jobject, jint);

/*
 * Class:     pipe_hla_SimDSPNModule_test_jni_MetisC2JTest
 * Method:    Function3
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_pipe_hla_SimDSPNModule_test_jni_MetisC2JTest_Function3
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     pipe_hla_SimDSPNModule_test_jni_MetisC2JTest
 * Method:    Function4
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_pipe_hla_SimDSPNModule_test_jni_MetisC2JTest_Function4
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     pipe_hla_SimDSPNModule_test_jni_MetisC2JTest
 * Method:    Function5
 * Signature: (III[I)I
 */
JNIEXPORT jint JNICALL Java_pipe_hla_SimDSPNModule_test_jni_MetisC2JTest_Function5
  (JNIEnv *, jobject, jint, jint, jint, jintArray);

/*
 * Class:     pipe_hla_SimDSPNModule_test_jni_MetisC2JTest
 * Method:    Function6
 * Signature: (III[I[I)I
 */
JNIEXPORT jint JNICALL Java_pipe_hla_SimDSPNModule_test_jni_MetisC2JTest_Function6
  (JNIEnv *, jobject, jint, jint, jint, jintArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
